SCREEN_TITLE = "pySNOOPY"

TILE_SCALING = 2

SCREEN_HEIGHT = 360 * TILE_SCALING
SCREEN_WIDTH = 594 * TILE_SCALING
SPRITE_PIXEL_SIZE = 18

CHARACTER_SCALING = TILE_SCALING * 1

PLAYER_START_X = SPRITE_PIXEL_SIZE * TILE_SCALING * 2
PLAYER_START_Y = SPRITE_PIXEL_SIZE * TILE_SCALING * 1

RIGHT_FACING = 0
LEFT_FACING = 1

PLAYER_MOVEMENT_SPEED = 3.5
GRAVITY = 0.16
PLAYER_JUMP_SPEED = 6.3
