SCREEN_TITLE = "pySNOOPY"

TILE_SCALING = 2

SCREEN_HEIGHT = 360 * TILE_SCALING
SCREEN_WIDTH = int(SCREEN_HEIGHT * (320 / 200))
SPRITE_PIXEL_SIZE = 18

CHARACTER_SCALING = 1.7
MOVING_HAZARD_SIZE_SCALE = 1

PLAYER_START_X = SPRITE_PIXEL_SIZE * TILE_SCALING * 2
PLAYER_START_Y = SPRITE_PIXEL_SIZE * TILE_SCALING * 1
PLAYER_GROUND_OFFSET = 0
PLAYER_GROUND_OFFSET_STEP = 0
SHOW_HITBOXES = True

RIGHT_FACING = 0
LEFT_FACING = 1

PLAYER_MOVEMENT_SPEED = 3.5
GRAVITY = 0.16
PLAYER_JUMP_SPEED = 6.5
RUN_SPEED_MULTIPLIER_STEP = 1.5
